#!/bin/zsh

preview_theme=${1:?Theme name is required}
repository_root=${0:A:h:h}

exec env -u NO_COLOR TERM=xterm-256color COLORTERM=truecolor \
    pwsh -NoLogo -NoProfile \
    -File "$repository_root/Scripts/Show-ThemePreview.ps1" \
    -Theme "$preview_theme"
