$repositoryRoot = Join-Path $PSScriptRoot '..' '..'
$commandCatalogPath = Join-Path $repositoryRoot 'docs/command-catalog.json'
$publishedExamples = @(Get-Content -LiteralPath $commandCatalogPath -Raw |
    ConvertFrom-Json |
    ForEach-Object { @{ Name = $_.Name; Example = $_.Example } })

Describe 'Generated command documentation' {
    BeforeAll {
        $script:RepositoryRoot = Join-Path $PSScriptRoot '..' '..'
        $script:Manifest = Import-PowerShellDataFile (Join-Path $script:RepositoryRoot 'TerminalSlides.psd1')
        $script:CatalogPath = Join-Path $script:RepositoryRoot 'docs/command-catalog.json'
        $script:WebsiteDataPath = Join-Path $script:RepositoryRoot 'docs/commands.json'
        Import-Module (Join-Path $script:RepositoryRoot 'TerminalSlides.psd1') -Force
    }

    It 'generates website data and native help from the command catalog' {
        { & (Join-Path $script:RepositoryRoot 'Scripts/Update-Documentation.ps1') -Check } |
            Should -Not -Throw

        $catalog = @(Get-Content -LiteralPath $script:CatalogPath -Raw | ConvertFrom-Json)
        $websiteData = @(Get-Content -LiteralPath $script:WebsiteDataPath -Raw | ConvertFrom-Json)
        ($websiteData | ConvertTo-Json -Depth 10) | Should -Be ($catalog | ConvertTo-Json -Depth 10)

        $nativeHelp = Get-Content (Join-Path $script:RepositoryRoot 'en-US/TerminalSlides-help.xml') -Raw
        $nativeHelp | Should -Match 'Generated by Scripts/Update-Documentation.ps1'
        ([xml]$nativeHelp).helpItems.command.Count | Should -Be $script:Manifest.FunctionsToExport.Count
    }

    It 'documents every exported command exactly once' {
        $catalog = @(Get-Content -LiteralPath $script:CatalogPath -Raw | ConvertFrom-Json)
        $documentedCommands = @($catalog.Name)

        $documentedCommands | Should -HaveCount $script:Manifest.FunctionsToExport.Count
        @($documentedCommands | Sort-Object -Unique) | Should -HaveCount $documentedCommands.Count
        Compare-Object $script:Manifest.FunctionsToExport $documentedCommands | Should -BeNullOrEmpty
    }

    It 'provides useful native help for every exported command' {
        $commonParameters = @(
            'Verbose', 'Debug', 'ErrorAction', 'WarningAction', 'InformationAction', 'ProgressAction',
            'ErrorVariable', 'WarningVariable', 'InformationVariable', 'OutVariable', 'OutBuffer', 'PipelineVariable'
        )
        foreach ($commandName in $script:Manifest.FunctionsToExport) {
            $help = Get-Help $commandName -Full
            $command = Get-Command $commandName
            $expectedParameters = @($command.Parameters.Keys | Where-Object { $_ -notin $commonParameters })
            $documentedParameters = @($help.Parameters.Parameter.Name | Where-Object { $_ })

            $help.Name | Should -Be $commandName
            [string]$help.Synopsis | Should -Not -BeNullOrEmpty
            [string]$help.Description.Text | Should -Not -BeNullOrEmpty
            @($help.Examples.Example) | Should -Not -BeNullOrEmpty
            @($help.Syntax.SyntaxItem) | Should -HaveCount $command.ParameterSets.Count
            $documentedParameters | Should -HaveCount $expectedParameters.Count
            if ($expectedParameters.Count -gt 0) {
                Compare-Object $expectedParameters $documentedParameters | Should -BeNullOrEmpty
            }
            foreach ($parameter in $help.Parameters.Parameter) {
                [string]$parameter.Type.Name | Should -Not -BeNullOrEmpty
                [string]$parameter.Required | Should -Match '^(true|false)$'
                [string]$parameter.Position | Should -Not -BeNullOrEmpty
            }
        }
    }

    It 'summarizes parameter-set-specific requirements accurately' {
        $help = Get-Help Add-SlideDiagram -Full
        $summaryParameters = @($help.Parameters.Parameter |
            Where-Object Name -in 'Content', 'Diagram')
        $syntaxParameters = @($help.Syntax.SyntaxItem.Parameter |
            Where-Object Name -in 'Content', 'Diagram')

        $summaryParameters | Should -HaveCount 2
        @($summaryParameters | Where-Object Required -eq 'false') | Should -HaveCount 2
        @($syntaxParameters | Where-Object Required -eq 'true') | Should -HaveCount 2
    }

    It 'exposes an accessible searchable command reference' {
        $index = Get-Content (Join-Path $script:RepositoryRoot 'docs/index.html') -Raw
        $clientScript = Get-Content (Join-Path $script:RepositoryRoot 'docs/script.js') -Raw

        $index | Should -Match 'id="commands"'
        $index | Should -Match 'id="command-search"'
        $index | Should -Match 'id="command-grid"'
        $index | Should -Not -Match 'TerminalSlides\.psd1'
        $clientScript | Should -Match ([regex]::Escape('fetch("./commands.json")'))
        $clientScript | Should -Match 'function isInteractiveTarget\(target\)'
        @([regex]::Matches($clientScript, 'if \(isInteractiveTarget\(event\.target\)\) return;')) |
            Should -HaveCount 1
    }

    It 'uses PSGallery-first onboarding in every user-facing entry point' {
        $index = Get-Content (Join-Path $script:RepositoryRoot 'docs/index.html') -Raw
        $readme = Get-Content (Join-Path $script:RepositoryRoot 'README.md') -Raw
        $contributing = Get-Content (Join-Path $script:RepositoryRoot 'CONTRIBUTING.md') -Raw
        $installCommand = 'Install-PSResource -Name TerminalSlides -Repository PSGallery -Scope CurrentUser -TrustRepository'

        foreach ($document in @($index, $readme, $contributing)) {
            $document | Should -Match ([regex]::Escape($installCommand))
            $document | Should -Not -Match 'Import-Module\s+\./TerminalSlides\.psd1'
            $document | Should -Not -Match '(?i)clone the repository.+import'
        }

        $index | Should -Match 'PowerShell Gallery'
        $index | Should -Match 'powershellgallery\.com/packages/TerminalSlides'
        $readme | Should -Match 'https://jorgeasaurus\.github\.io/TerminalSlides/'
    }

    It 'uses public README badge endpoints' {
        $readme = Get-Content (Join-Path $script:RepositoryRoot 'README.md') -Raw

        $readme | Should -Match 'img\.shields\.io/powershellgallery/v/TerminalSlides'
        $readme | Should -Not -Match 'actions/workflows/ci\.yml/badge\.svg'
    }

    It 'publishes a distinct terminal capture for every built-in theme' {
        $readme = Get-Content (Join-Path $script:RepositoryRoot 'README.md') -Raw
        $themeFiles = @(Get-ChildItem (Join-Path $script:RepositoryRoot 'Themes') -Filter '*.psd1')
        $hashes = [Collections.Generic.HashSet[string]]::new([StringComparer]::Ordinal)

        $themeFiles | Should -HaveCount 8
        @([regex]::Matches($readme, '(?m)^## Built-in themes\r?$')) | Should -HaveCount 1
        foreach ($themeFile in $themeFiles) {
            $slug = [regex]::Replace(
                $themeFile.BaseName,
                '(?<=[a-z0-9])(?=[A-Z])',
                '-'
            ).ToLowerInvariant()
            $relativePath = "docs/theme-previews/$slug.png"
            $imagePath = Join-Path $script:RepositoryRoot $relativePath

            $imagePath | Should -Exist
            $bytes = [IO.File]::ReadAllBytes($imagePath)
            $bytes[0..7] | Should -Be @(137, 80, 78, 71, 13, 10, 26, 10)
            [BitConverter]::ToInt32([byte[]]@($bytes[19], $bytes[18], $bytes[17], $bytes[16]), 0) |
                Should -Be 1600
            [BitConverter]::ToInt32([byte[]]@($bytes[23], $bytes[22], $bytes[21], $bytes[20]), 0) |
                Should -Be 900
            $hashes.Add((Get-FileHash -LiteralPath $imagePath -Algorithm SHA256).Hash) |
                Should -BeTrue
            @([regex]::Matches($readme, [regex]::Escape($relativePath))) |
                Should -HaveCount 1
        }
    }

    It 'uses the exact demo slide photo as its social preview image' {
        $demo = Start-TerminalSlidesDemo -PassThru
        $slideImage = $demo.Slides.Elements |
            Where-Object Kind -eq ([TerminalSlides.Schema.V1.ElementKind]::Image) |
            Select-Object -First 1
        $socialImage = Join-Path $script:RepositoryRoot 'docs/presentation-team-photo.jpg'
        $index = Get-Content (Join-Path $script:RepositoryRoot 'docs/index.html') -Raw

        $socialImage | Should -Exist
        $index | Should -Match 'og:image[^>]+presentation-team-photo\.jpg'
        $index | Should -Match 'twitter:image[^>]+presentation-team-photo\.jpg'
        (Get-FileHash $socialImage).Hash | Should -Be (Get-FileHash $slideImage.Payload.Path).Hash
    }
}

Describe 'Published command examples' {
    BeforeAll {
        Import-Module (Join-Path $PSScriptRoot '..' '..' 'TerminalSlides.psd1') -Force
    }

    BeforeEach {
        $deck = New-TerminalPresentation -Title 'Documentation fixture'
        foreach ($title in 'Agenda', 'Roadmap', 'Details', 'Appendix') {
            $deck | Add-TerminalSlide -Title $title -Content { Add-SlideText "Fixture $title" } | Out-Null
        }
        Mock Show-TerminalPresentation {}
        Mock Start-TerminalSlidesDemo {
            param(
                [string]$Name = 'TerminalSlides',
                [switch]$PassThru
            )

            if ($PassThru) { New-TerminalPresentation -Title "$Name demo fixture" }
        }

        foreach ($temporaryName in 'terminalslides-deck.html', 'terminalslides-deck.json') {
            $path = Join-Path ([IO.Path]::GetTempPath()) $temporaryName
            if (Test-Path -LiteralPath $path) { Remove-Item -LiteralPath $path -Force }
        }
    }

    AfterEach {
        foreach ($temporaryName in 'terminalslides-deck.html', 'terminalslides-deck.json') {
            $path = Join-Path ([IO.Path]::GetTempPath()) $temporaryName
            if (Test-Path -LiteralPath $path) { Remove-Item -LiteralPath $path -Force }
        }
    }

    It 'models the demo PassThru output contract' {
        @(Start-TerminalSlidesDemo) | Should -HaveCount 0
        (Start-TerminalSlidesDemo -PassThru).Title | Should -Be 'TerminalSlides demo fixture'
        (Start-TerminalSlidesDemo -Name IntuneHydrationKit -PassThru).Title |
            Should -Be 'IntuneHydrationKit demo fixture'
    }

    It 'executes the <Name> example against controlled fixtures' -ForEach $publishedExamples {
        $tokens = $null
        $parseErrors = $null
        [void][System.Management.Automation.Language.Parser]::ParseInput(
            $Example,
            [ref]$tokens,
            [ref]$parseErrors
        )
        $parseErrors | Should -BeNullOrEmpty

        { . ([scriptblock]::Create($Example)) } | Should -Not -Throw
    }
}
