$repositoryRoot = Join-Path $PSScriptRoot '..' '..'
$commandCatalogPath = Join-Path $repositoryRoot 'docs/command-catalog.json'
$publishedExamples = @(Get-Content -LiteralPath $commandCatalogPath -Raw |
    ConvertFrom-Json |
    ForEach-Object { @{ Name = $_.Name; Example = $_.Example } })

Describe 'Generated command documentation' {
    BeforeAll {
        $script:RepositoryRoot = Join-Path $PSScriptRoot '..' '..'
        $script:Manifest = Import-PowerShellDataFile (Join-Path $script:RepositoryRoot 'TerminalSlides.psd1')
        $script:CatalogPath = Join-Path $script:RepositoryRoot 'docs/command-catalog.json'
        $script:WebsiteDataPath = Join-Path $script:RepositoryRoot 'docs/commands.json'
        Import-Module (Join-Path $script:RepositoryRoot 'TerminalSlides.psd1') -Force
    }

    It 'generates website data and native help from the command catalog' {
        { & (Join-Path $script:RepositoryRoot 'Scripts/Update-Documentation.ps1') -Check } |
            Should -Not -Throw

        $catalog = @(Get-Content -LiteralPath $script:CatalogPath -Raw | ConvertFrom-Json)
        $websiteData = @(Get-Content -LiteralPath $script:WebsiteDataPath -Raw | ConvertFrom-Json)
        ($websiteData | ConvertTo-Json -Depth 10) | Should -Be ($catalog | ConvertTo-Json -Depth 10)

        $nativeHelp = Get-Content (Join-Path $script:RepositoryRoot 'en-US/TerminalSlides-help.xml') -Raw
        $nativeHelp | Should -Match 'Generated by Scripts/Update-Documentation.ps1'
        ([xml]$nativeHelp).helpItems.command.Count | Should -Be $script:Manifest.FunctionsToExport.Count
    }

    It 'documents every exported command exactly once' {
        $catalog = @(Get-Content -LiteralPath $script:CatalogPath -Raw | ConvertFrom-Json)
        $documentedCommands = @($catalog.Name)

        $documentedCommands | Should -HaveCount $script:Manifest.FunctionsToExport.Count
        @($documentedCommands | Sort-Object -Unique) | Should -HaveCount $documentedCommands.Count
        Compare-Object $script:Manifest.FunctionsToExport $documentedCommands | Should -BeNullOrEmpty
    }

    It 'provides useful native help for every exported command' {
        $commonParameters = @(
            'Verbose', 'Debug', 'ErrorAction', 'WarningAction', 'InformationAction', 'ProgressAction',
            'ErrorVariable', 'WarningVariable', 'InformationVariable', 'OutVariable', 'OutBuffer', 'PipelineVariable'
        )
        foreach ($commandName in $script:Manifest.FunctionsToExport) {
            $help = Get-Help $commandName -Full
            $command = Get-Command $commandName
            $expectedParameters = @($command.Parameters.Keys | Where-Object { $_ -notin $commonParameters })
            $documentedParameters = @($help.Parameters.Parameter.Name | Where-Object { $_ })

            $help.Name | Should -Be $commandName
            [string]$help.Synopsis | Should -Not -BeNullOrEmpty
            [string]$help.Description.Text | Should -Not -BeNullOrEmpty
            @($help.Examples.Example) | Should -Not -BeNullOrEmpty
            @($help.Syntax.SyntaxItem) | Should -HaveCount $command.ParameterSets.Count
            $documentedParameters | Should -HaveCount $expectedParameters.Count
            if ($expectedParameters.Count -gt 0) {
                Compare-Object $expectedParameters $documentedParameters | Should -BeNullOrEmpty
            }
            foreach ($parameter in $help.Parameters.Parameter) {
                [string]$parameter.Type.Name | Should -Not -BeNullOrEmpty
                [string]$parameter.Required | Should -Match '^(true|false)$'
                [string]$parameter.Position | Should -Not -BeNullOrEmpty
            }
        }
    }

    It 'exposes an accessible searchable command reference' {
        $index = Get-Content (Join-Path $script:RepositoryRoot 'docs/index.html') -Raw
        $clientScript = Get-Content (Join-Path $script:RepositoryRoot 'docs/script.js') -Raw

        $index | Should -Match 'id="commands"'
        $index | Should -Match 'id="command-search"'
        $index | Should -Match 'id="command-grid"'
        $clientScript | Should -Match ([regex]::Escape('fetch("./commands.json")'))
        $clientScript | Should -Match 'function isInteractiveTarget\(target\)'
        @([regex]::Matches($clientScript, 'if \(isInteractiveTarget\(event\.target\)\) return;')) |
            Should -HaveCount 1
    }

    It 'does not claim unpublished Gallery or Pages locations' {
        $index = Get-Content (Join-Path $script:RepositoryRoot 'docs/index.html') -Raw
        $readme = Get-Content (Join-Path $script:RepositoryRoot 'README.md') -Raw

        $index | Should -Not -Match 'Install-Module TerminalSlides'
        $index | Should -Not -Match 'PowerShell Gallery'
        $index | Should -Not -Match 'powershellgallery\.com'
        $index | Should -Not -Match 'jorgeasaurus\.github\.io'
        $readme | Should -Not -Match 'Install-Module\s+TerminalSlides'
        $readme | Should -Not -Match '(?m)^Import-Module\s+TerminalSlides\s*$'
    }

    It 'uses the exact demo slide photo as its social preview image' {
        $demo = Start-TerminalSlidesDemo -PassThru
        $slideImage = $demo.Slides.Elements |
            Where-Object Kind -eq ([TerminalSlides.Schema.V1.ElementKind]::Image) |
            Select-Object -First 1
        $socialImage = Join-Path $script:RepositoryRoot 'docs/presentation-team-photo.jpg'
        $index = Get-Content (Join-Path $script:RepositoryRoot 'docs/index.html') -Raw

        $socialImage | Should -Exist
        $index | Should -Match 'og:image[^>]+presentation-team-photo\.jpg'
        $index | Should -Match 'twitter:image[^>]+presentation-team-photo\.jpg'
        (Get-FileHash $socialImage).Hash | Should -Be (Get-FileHash $slideImage.Payload.Path).Hash
    }
}

Describe 'Published command examples' {
    BeforeAll {
        Import-Module (Join-Path $PSScriptRoot '..' '..' 'TerminalSlides.psd1') -Force
    }

    BeforeEach {
        $deck = New-TerminalPresentation -Title 'Documentation fixture'
        foreach ($title in 'Agenda', 'Roadmap', 'Details', 'Appendix') {
            $deck | Add-TerminalSlide -Title $title -Content { Add-SlideText "Fixture $title" } | Out-Null
        }
        Mock Show-TerminalPresentation {}
        Mock Start-TerminalSlidesDemo { New-TerminalPresentation -Title 'Demo fixture' }

        foreach ($temporaryName in 'terminalslides-deck.html', 'terminalslides-deck.json') {
            $path = Join-Path ([IO.Path]::GetTempPath()) $temporaryName
            if (Test-Path -LiteralPath $path) { Remove-Item -LiteralPath $path -Force }
        }
    }

    AfterEach {
        foreach ($temporaryName in 'terminalslides-deck.html', 'terminalslides-deck.json') {
            $path = Join-Path ([IO.Path]::GetTempPath()) $temporaryName
            if (Test-Path -LiteralPath $path) { Remove-Item -LiteralPath $path -Force }
        }
    }

    It 'executes the <Name> example against controlled fixtures' -ForEach $publishedExamples {
        $tokens = $null
        $parseErrors = $null
        [void][System.Management.Automation.Language.Parser]::ParseInput(
            $Example,
            [ref]$tokens,
            [ref]$parseErrors
        )
        $parseErrors | Should -BeNullOrEmpty

        { . ([scriptblock]::Create($Example)) } | Should -Not -Throw
    }
}
